trigger: none

pool:
  vmImage: 'windows-latest'

steps:

- task: UseDotNet@2
  displayName: 'Use dotnet 3.1'
  inputs:
    version: 3.1.x

- task: UseDotNet@2
  displayName: 'Use dotnet 6.0'
  inputs:
    version: 6.0.x

- script: |
    npm install --global @cyclonedx/cyclonedx-npm
    npm i -g typescript ts-node
    npm install --production --unsafe-perm
    npm dedupe
  displayName: 'Run a multi-line script'

- task: MicrosoftSecurityDevOps@1
  displayName: 'Run Microsoft Security DevOps'
